name: Ping Render Server

on:
  schedule:
    - cron: '0 * * * *' # para que suene cada hora

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer ping al backend de Render
        run: curl -s https://api-proyecto-jkec.onrender.com/api/recordatorio/enviar
